language: java
sudo: required
dist: trusty
jdk:
    - oraclejdk8
services:
  - docker
notifications:
    email:
    recipients:
        - g.kokosinski@gmail.com


install: ./mvnw install -DskipTests -B -q

script:
  - ./mvnw test
  - ./bin/setup_devenv.sh
  - java -jar target/autobet-0.1-SNAPSHOT-executable.jar stats -c 10000
  - java -jar target/autobet-0.1-SNAPSHOT-executable.jar eval -c 1000 -s random
  - java -jar target/autobet-0.1-SNAPSHOT-executable.jar eval -c 1000 -s goal_based

after_success:
    - |
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker commit mysql_autobet kokosing/mysql_autobet:latest
        docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
        docker push kokosing/mysql_autobet:latest
      fi
