language: java
sudo: required
dist: trusty
jdk:
    - oraclejdk8
services:
  - docker
notifications:
    email:
    recipients:
        - g.kokosinski@gmail.com


install: ./mvnw install -DskipTests -B -q

script:
  - ./mvnw test
  - | 
    if ! ./bin/devenv_update.sh; then
      ./bin/devenv_create.sh
      ./bin/devenv_update.sh
    fi

after_success:
    - |
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker commit mysql_autobet kokosing/mysql_autobet:latest
        docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
        docker push kokosing/mysql_autobet:latest
      fi
